namespace Hades.Constants;

public enum ArmorLocation
{
    Base,
    Dlc,
    Both,
}

public readonly record struct ArmorEntry(int Id, string Name, ArmorLocation Location);

public static class Armors
{
    public static IEnumerable<ArmorEntry> Get(
        ArmorEntry[] source,
        ArmorLocation? location = null
    ) =>
        location switch
        {
            null => source,
            ArmorLocation.Both => source.Where(e =>
                e.Location == ArmorLocation.Base || e.Location == ArmorLocation.Dlc
            ),
            _ => source.Where(e => e.Location == location),
        };
}

public static class Gauntlets
{
    public static readonly ArmorEntry[] All =
    {
        new(40200, "Iron Gauntlets", ArmorLocation.Base),
        new(50200, "Kaiden Gauntlets", ArmorLocation.Base),
        new(60200, "Drake Knight Gauntlets", ArmorLocation.Base),
        new(80200, "Scaled Gauntlets", ArmorLocation.Base),
        new(90200, "Perfumer Gloves", ArmorLocation.Base),
        new(100200, "Traveler's Gloves", ArmorLocation.Base),
        new(120200, "Alberich's Bracers", ArmorLocation.Base),
        new(130200, "Spellblade's Gloves", ArmorLocation.Base),
        new(140200, "Bull-Goat Gauntlets", ArmorLocation.Base),
        new(150200, "Ronin's Gauntlets", ArmorLocation.Base),
        new(170200, "Blaidd's Gauntlets", ArmorLocation.Base),
        new(180200, "Black Knife Gauntlets", ArmorLocation.Base),
        new(190200, "Exile Gauntlets", ArmorLocation.Base),
        new(200200, "Banished Knight Gauntlets", ArmorLocation.Base),
        new(210200, "Briar Gauntlets", ArmorLocation.Base),
        new(230200, "Night's Cavalry Gauntlets", ArmorLocation.Base),
        new(240200, "Blue Silver Bracelets", ArmorLocation.Base),
        new(260200, "Malformed Dragon Gauntlets", ArmorLocation.Base),
        new(270200, "Tree Sentinel Gauntlets", ArmorLocation.Base),
        new(280200, "Royal Knight Gauntlets", ArmorLocation.Base),
        new(290200, "Nox Bracelets", ArmorLocation.Base),
        new(330200, "Guardian Bracers", ArmorLocation.Base),
        new(340200, "Cleanrot Gauntlets", ArmorLocation.Base),
        new(350200, "Fire Monk Gauntlets", ArmorLocation.Base),
        new(351200, "Blackflame Monk Gauntlets", ArmorLocation.Base),
        new(360200, "Fire Prelate Gauntlets", ArmorLocation.Base),
        new(420200, "Vulgar Militia Gauntlets", ArmorLocation.Base),
        new(460200, "Elden Lord Bracers", ArmorLocation.Base),
        new(470200, "Radahn's Gauntlets", ArmorLocation.Base),
        new(510200, "Queen's Bracelets", ArmorLocation.Base),
        new(520200, "Godskin Apostle Bracelets", ArmorLocation.Base),
        new(530200, "Godskin Noble Bracelets", ArmorLocation.Base),
        new(540200, "Depraved Perfumer Gloves", ArmorLocation.Base),
        new(570200, "Crucible Gauntlets", ArmorLocation.Base),
        new(580200, "Lusat's Manchettes", ArmorLocation.Base),
        new(581200, "Azur's Manchettes", ArmorLocation.Base),
        new(590200, "All-Knowing Gauntlets", ArmorLocation.Base),
        new(600200, "Twinned Gauntlets", ArmorLocation.Base),
        new(610200, "Ragged Gloves", ArmorLocation.Base),
        new(630200, "Astrologer Gloves", ArmorLocation.Base),
        new(640200, "Lionel's Gauntlets", ArmorLocation.Base),
        new(650200, "Hoslow's Gauntlets", ArmorLocation.Base),
        new(660200, "Vagabond Knight Gauntlets", ArmorLocation.Base),
        new(670200, "Warrior Gauntlets", ArmorLocation.Base),
        new(680200, "War Surgeon Gloves", ArmorLocation.Base),
        new(690200, "Royal Remains Gauntlets", ArmorLocation.Base),
        new(700200, "Brave's Bracer", ArmorLocation.Base),
        new(720200, "Beast Champion Gauntlets", ArmorLocation.Base),
        new(730200, "Champion Bracers", ArmorLocation.Base),
        new(740200, "Noble's Gloves", ArmorLocation.Base),
        new(760200, "Maliketh's Gauntlets", ArmorLocation.Base),
        new(770200, "Malenia's Gauntlet", ArmorLocation.Base),
        new(780200, "Veteran's Gauntlets", ArmorLocation.Base),
        new(790200, "Bloodhound Knight Gauntlets", ArmorLocation.Base),
        new(830200, "Sorcerer Manchettes", ArmorLocation.Base),
        new(860200, "Raging Wolf Gauntlets", ArmorLocation.Base),
        new(870200, "Land of Reeds Gauntlets", ArmorLocation.Base),
        new(872200, "White Reed Gauntlets", ArmorLocation.Base),
        new(880200, "Confessor Gloves", ArmorLocation.Base),
        new(900200, "Traveling Maiden Gloves", ArmorLocation.Base),
        new(910200, "Preceptor's Gloves", ArmorLocation.Base),
        new(930200, "Bandit Manchettes", ArmorLocation.Base),
        new(940200, "Eccentric's Manchettes", ArmorLocation.Base),
        new(950200, "Fingerprint Gauntlets", ArmorLocation.Base),
        new(963200, "Bloodsoaked Manchettes", ArmorLocation.Base),
        new(970200, "Omen Gauntlets", ArmorLocation.Base),
        new(980200, "Carian Knight Gauntlets", ArmorLocation.Base),
        new(990200, "Errant Sorcerer Manchettes", ArmorLocation.Base),
        new(1000200, "Battlemage Manchettes", ArmorLocation.Base),
        new(1020200, "Traveler's Manchettes", ArmorLocation.Base),
        new(1040200, "Gold Bracelets", ArmorLocation.Base),
        new(1070200, "Zamor Bracelets", ArmorLocation.Base),
        new(1100200, "Chain Gauntlets", ArmorLocation.Base),
        new(1130200, "Mushroom Arms", ArmorLocation.Base),
        new(1400200, "Leather Gloves", ArmorLocation.Base),
        new(1500200, "Knight Gauntlets", ArmorLocation.Base),
        new(1700200, "Godrick Soldier Gauntlets", ArmorLocation.Base),
        new(1710200, "Raya Lucarian Gauntlets", ArmorLocation.Base),
        new(1720200, "Leyndell Soldier Gauntlets", ArmorLocation.Base),
        new(1730200, "Radahn Soldier Gauntlets", ArmorLocation.Base),
        new(1740200, "Mausoleum Gauntlets", ArmorLocation.Base),
        new(1750200, "Haligtree Gauntlets", ArmorLocation.Base),
        new(1760200, "Gelmir Knight Gauntlets", ArmorLocation.Base),
        new(1770200, "Godrick Knight Gauntlets", ArmorLocation.Base),
        new(1780200, "Cuckoo Knight Gauntlets", ArmorLocation.Base),
        new(1790200, "Leyndell Knight Gauntlets", ArmorLocation.Base),
        new(1800200, "Redmane Knight Gauntlets", ArmorLocation.Base),
        new(1810200, "Mausoleum Knight Gauntlets", ArmorLocation.Base),
        new(1820200, "Haligtree Knight Gauntlets", ArmorLocation.Base),
        new(1830200, "Foot Soldier Gauntlets", ArmorLocation.Base),
        new(1890200, "Omenkiller Long Gloves", ArmorLocation.Base),
        new(1980200, "Highwayman Gauntlets", ArmorLocation.Base),
        new(3000200, "Dryleaf Arm Wraps", ArmorLocation.Dlc),
        new(3010200, "Gaius's Gauntlets", ArmorLocation.Dlc),
        new(5000200, "Oathseeker Knight Gauntlets", ArmorLocation.Dlc),
        new(5010200, "Verdigris Gauntlets", ArmorLocation.Dlc),
        new(5020200, "Iron Rivet Gauntlets", ArmorLocation.Dlc),
        new(5030200, "Thiollier's Gloves", ArmorLocation.Dlc),
        new(5060200, "High Priest Gloves", ArmorLocation.Dlc),
        new(5070200, "Braided Arm Wraps", ArmorLocation.Dlc),
        new(5080200, "Dancer's Bracer", ArmorLocation.Dlc),
        new(5090200, "Gauntlets of Night", ArmorLocation.Dlc),
        new(5100200, "Igon's Gauntlets", ArmorLocation.Dlc),
        new(5110200, "Ansbach's Manchettes", ArmorLocation.Dlc),
        new(5120200, "Freyja's Gauntlets", ArmorLocation.Dlc),
        new(5130200, "Gauntlets of Solitude", ArmorLocation.Dlc),
        new(5140200, "Messmer Soldier Gauntlets", ArmorLocation.Dlc),
        new(5150200, "Black Knight Gauntlets", ArmorLocation.Dlc),
        new(5160200, "Rakshasa Gauntlets", ArmorLocation.Dlc),
        new(5180200, "Fire Knight Gauntlets", ArmorLocation.Dlc),
        new(5190200, "Leather Arm Wraps", ArmorLocation.Dlc),
        new(5200200, "Death Knight Gauntlets", ArmorLocation.Dlc),
        new(5210200, "Ascetic's Wrist Guards", ArmorLocation.Dlc),
        new(5220200, "Messmer's Gauntlets", ArmorLocation.Dlc),
        new(5230200, "Gravebird Bracelets", ArmorLocation.Dlc),
        new(5240200, "Common Soldier Gauntlets", ArmorLocation.Dlc),
        new(5250200, "Horned Warrior Gauntlets", ArmorLocation.Dlc),
        new(5253200, "Divine Bird Warrior Gauntlets", ArmorLocation.Dlc),
        new(5260200, "Rellana's Gloves", ArmorLocation.Dlc),
        new(5270200, "Young Lion's Gauntlets", ArmorLocation.Dlc),
        new(5280200, "Shadow Militiaman Gauntlets", ArmorLocation.Dlc),
    };
}

public static class Greaves
{
    public static readonly ArmorEntry[] All =
    {
        new(120300, "Alberich's Trousers", ArmorLocation.Base),
        new(590300, "All-Knowing Greaves", ArmorLocation.Base),
        new(370300, "Aristocrat Boots", ArmorLocation.Base),
        new(630300, "Astrologer Trousers", ArmorLocation.Base),
        new(930300, "Bandit Boots", ArmorLocation.Base),
        new(200300, "Banished Knight Greaves", ArmorLocation.Base),
        new(1000300, "Battlemage Legwraps", ArmorLocation.Base),
        new(720300, "Beast Champion Greaves", ArmorLocation.Base),
        new(180300, "Black Knife Greaves", ArmorLocation.Base),
        new(351300, "Blackflame Monk Greaves", ArmorLocation.Base),
        new(170300, "Blaidd's Greaves", ArmorLocation.Base),
        new(790300, "Bloodhound Knight Greaves", ArmorLocation.Base),
        new(240300, "Blue Silver Mail Skirt", ArmorLocation.Base),
        new(700300, "Brave's Legwraps", ArmorLocation.Base),
        new(210300, "Briar Greaves", ArmorLocation.Base),
        new(140300, "Bull-Goat Greaves", ArmorLocation.Base),
        new(980300, "Carian Knight Greaves", ArmorLocation.Base),
        new(1100300, "Chain Leggings", ArmorLocation.Base),
        new(730300, "Champion Gaiters", ArmorLocation.Base),
        new(340300, "Cleanrot Greaves", ArmorLocation.Base),
        new(160300, "Cloth Trousers", ArmorLocation.Base),
        new(810300, "Commoner's Shoes", ArmorLocation.Base),
        new(880300, "Confessor Boots", ArmorLocation.Base),
        new(960300, "Consort's Trousers", ArmorLocation.Base),
        new(570300, "Crucible Greaves", ArmorLocation.Base),
        new(1780300, "Cuckoo Knight Greaves", ArmorLocation.Base),
        new(540300, "Depraved Perfumer Trousers", ArmorLocation.Base),
        new(60300, "Drake Knight Greaves", ArmorLocation.Base),
        new(310300, "Duelist Greaves", ArmorLocation.Base),
        new(940300, "Eccentric's Breeches", ArmorLocation.Base),
        new(460300, "Elden Lord Greaves", ArmorLocation.Base),
        new(990300, "Errant Sorcerer Boots", ArmorLocation.Base),
        new(190300, "Exile Greaves", ArmorLocation.Base),
        new(902300, "Finger Maiden Shoes", ArmorLocation.Base),
        new(950300, "Fingerprint Greaves", ArmorLocation.Base),
        new(350300, "Fire Monk Greaves", ArmorLocation.Base),
        new(360300, "Fire Prelate Greaves", ArmorLocation.Base),
        new(1830300, "Foot Soldier Greaves", ArmorLocation.Base),
        new(300300, "Fur Leggings", ArmorLocation.Base),
        new(1760300, "Gelmir Knight Greaves", ArmorLocation.Base),
        new(1770300, "Godrick Knight Greaves", ArmorLocation.Base),
        new(1700300, "Godrick Soldier Greaves", ArmorLocation.Base),
        new(520300, "Godskin Apostle Trousers", ArmorLocation.Base),
        new(530300, "Godskin Noble Trousers", ArmorLocation.Base),
        new(1040300, "Gold Waistwrap", ArmorLocation.Base),
        new(330300, "Guardian Greaves", ArmorLocation.Base),
        new(1750300, "Haligtree Greaves", ArmorLocation.Base),
        new(1820300, "Haligtree Knight Greaves", ArmorLocation.Base),
        new(650300, "Hoslow's Greaves", ArmorLocation.Base),
        new(50300, "Kaiden Trousers", ArmorLocation.Base),
        new(1500300, "Knight Greaves", ArmorLocation.Base),
        new(870300, "Land of Reeds Greaves", ArmorLocation.Base),
        new(1400300, "Leather Boots", ArmorLocation.Base),
        new(40300, "Leather Trousers", ArmorLocation.Base),
        new(1790300, "Leyndell Knight Greaves", ArmorLocation.Base),
        new(1720300, "Leyndell Soldier Greaves", ArmorLocation.Base),
        new(640300, "Lionel's Greaves", ArmorLocation.Base),
        new(770300, "Malenia's Greaves", ArmorLocation.Base),
        new(260300, "Malformed Dragon Greaves", ArmorLocation.Base),
        new(760300, "Maliketh's Greaves", ArmorLocation.Base),
        new(1740300, "Mausoleum Greaves", ArmorLocation.Base),
        new(1810300, "Mausoleum Knight Greaves", ArmorLocation.Base),
        new(1130300, "Mushroom Legs", ArmorLocation.Base),
        new(230300, "Night's Cavalry Greaves", ArmorLocation.Base),
        new(740300, "Noble's Trousers", ArmorLocation.Base),
        new(250300, "Nomadic Merchant's Trousers", ArmorLocation.Base),
        new(290300, "Nox Greaves", ArmorLocation.Base),
        new(390300, "Old Aristocrat Shoes", ArmorLocation.Base),
        new(580300, "Old Sorcerer's Legwraps", ArmorLocation.Base),
        new(970300, "Omen Greaves", ArmorLocation.Base),
        new(1890300, "Omenkiller Boots", ArmorLocation.Base),
        new(220300, "Page Trousers", ArmorLocation.Base),
        new(90300, "Perfumer Sarong", ArmorLocation.Base),
        new(910300, "Preceptor's Trousers", ArmorLocation.Base),
        new(890300, "Prisoner Trousers", ArmorLocation.Base),
        new(620300, "Prophet Trousers", ArmorLocation.Base),
        new(510300, "Queen's Leggings", ArmorLocation.Base),
        new(1730300, "Radahn Soldier Greaves", ArmorLocation.Base),
        new(470300, "Radahn's Greaves", ArmorLocation.Base),
        new(610300, "Ragged Loincloth", ArmorLocation.Base),
        new(860300, "Raging Wolf Greaves", ArmorLocation.Base),
        new(1710300, "Raya Lucarian Greaves", ArmorLocation.Base),
        new(1800300, "Redmane Knight Greaves", ArmorLocation.Base),
        new(150300, "Ronin's Greaves", ArmorLocation.Base),
        new(2000300, "Rotten Duelist Greaves", ArmorLocation.Base),
        new(280300, "Royal Knight Greaves", ArmorLocation.Base),
        new(690300, "Royal Remains Greaves", ArmorLocation.Base),
        new(430300, "Sage Trousers", ArmorLocation.Base),
        new(320300, "Sanguine Noble Waistcloth", ArmorLocation.Base),
        new(80300, "Scaled Greaves", ArmorLocation.Base),
        new(301300, "Shaman Leggings", ArmorLocation.Base),
        new(1010300, "Snow Witch Skirt", ArmorLocation.Base),
        new(830300, "Sorcerer Leggings", ArmorLocation.Base),
        new(130300, "Spellblade's Trousers", ArmorLocation.Base),
        new(1020300, "Traveler's Boots", ArmorLocation.Base),
        new(100300, "Traveler's Slops", ArmorLocation.Base),
        new(900300, "Traveling Maiden Boots", ArmorLocation.Base),
        new(270300, "Tree Sentinel Greaves", ArmorLocation.Base),
        new(600300, "Twinned Greaves", ArmorLocation.Base),
        new(660300, "Vagabond Knight Greaves", ArmorLocation.Base),
        new(780300, "Veteran's Greaves", ArmorLocation.Base),
        new(420300, "Vulgar Militia Greaves", ArmorLocation.Base),
        new(680300, "War Surgeon Trousers", ArmorLocation.Base),
        new(670300, "Warrior Greaves", ArmorLocation.Base),
        new(872300, "White Reed Greaves", ArmorLocation.Base),
        new(1070300, "Zamor Legwraps", ArmorLocation.Base),
        new(3000300, "Dryleaf Cuissardes", ArmorLocation.Dlc),
        new(3010300, "Gaius's Greaves", ArmorLocation.Dlc),
        new(5000300, "Oathseeker Knight Greaves", ArmorLocation.Dlc),
        new(5010300, "Verdigris Greaves", ArmorLocation.Dlc),
        new(5020300, "Iron Rivet Greaves", ArmorLocation.Dlc),
        new(5030300, "Thiollier's Trousers", ArmorLocation.Dlc),
        new(5060300, "High Priest Undergarments", ArmorLocation.Dlc),
        new(5070300, "Soiled Loincloth", ArmorLocation.Dlc),
        new(5080300, "Dancer's Trousers", ArmorLocation.Dlc),
        new(5090300, "Greaves of Night", ArmorLocation.Dlc),
        new(5100300, "Igon's Loincloth", ArmorLocation.Dlc),
        new(5110300, "Ansbach's Boots", ArmorLocation.Dlc),
        new(5120300, "Freyja's Greaves", ArmorLocation.Dlc),
        new(5130300, "Greaves of Solitude", ArmorLocation.Dlc),
        new(5140300, "Messmer Soldier Greaves", ArmorLocation.Dlc),
        new(5150300, "Black Knight Greaves", ArmorLocation.Dlc),
        new(5160300, "Rakshasa Greaves", ArmorLocation.Dlc),
        new(5180300, "Fire Knight Greaves", ArmorLocation.Dlc),
        new(5190300, "Leather Leg Wraps", ArmorLocation.Dlc),
        new(5200300, "Death Knight Greaves", ArmorLocation.Dlc),
        new(5210300, "Ascetic's Ankle Guards", ArmorLocation.Dlc),
        new(5220300, "Messmer's Greaves", ArmorLocation.Dlc),
        new(5230300, "Gravebird Anklets", ArmorLocation.Dlc),
        new(5240300, "Common Soldier Greaves", ArmorLocation.Dlc),
        new(5250300, "Horned Warrior Greaves", ArmorLocation.Dlc),
        new(5253300, "Divine Bird Warrior Greaves", ArmorLocation.Dlc),
        new(5260300, "Rellana's Greaves", ArmorLocation.Dlc),
        new(5270300, "Young Lion's Greaves", ArmorLocation.Dlc),
        new(5280300, "Shadow Militiaman Greaves", ArmorLocation.Dlc),
    };
}

public static class Helms
{
    public static readonly ArmorEntry[] All =
    {
        new(40000, "Iron Helmet", ArmorLocation.Base),
        new(50000, "Kaiden Helm", ArmorLocation.Base),
        new(60000, "Drake Knight Helm", ArmorLocation.Base),
        new(61000, "Drake Knight Helm (Altered)", ArmorLocation.Base),
        new(80000, "Scaled Helm", ArmorLocation.Base),
        new(90000, "Perfumer Hood", ArmorLocation.Base),
        new(100000, "Traveler's Hat", ArmorLocation.Base),
        new(120000, "Alberich's Pointed Hat", ArmorLocation.Base),
        new(121000, "Alberich's Pointed Hat (Altered)", ArmorLocation.Base),
        new(130000, "Spellblade's Pointed Hat", ArmorLocation.Base),
        new(140000, "Bull-Goat Helm", ArmorLocation.Base),
        new(150000, "Iron Kasa", ArmorLocation.Base),
        new(160000, "Guilty Hood", ArmorLocation.Base),
        new(170000, "Black Wolf Mask", ArmorLocation.Base),
        new(180000, "Black Knife Hood", ArmorLocation.Base),
        new(190000, "Exile Hood", ArmorLocation.Base),
        new(200000, "Banished Knight Helm", ArmorLocation.Base),
        new(201000, "Banished Knight Helm (Altered)", ArmorLocation.Base),
        new(210000, "Briar Helm", ArmorLocation.Base),
        new(220000, "Page Hood", ArmorLocation.Base),
        new(230000, "Night's Cavalry Helm", ArmorLocation.Base),
        new(231000, "Night's Cavalry Helm (Altered)", ArmorLocation.Base),
        new(240000, "Blue Silver Mail Hood", ArmorLocation.Base),
        new(250000, "Nomadic Merchant's Chapeau", ArmorLocation.Base),
        new(260000, "Malformed Dragon Helm", ArmorLocation.Base),
        new(270000, "Tree Sentinel Helm", ArmorLocation.Base),
        new(280000, "Royal Knight Helm", ArmorLocation.Base),
        new(290000, "Nox Monk Hood", ArmorLocation.Base),
        new(291000, "Nox Monk Hood (Altered)", ArmorLocation.Base),
        new(292000, "Nox Swordstress Crown", ArmorLocation.Base),
        new(293000, "Night Maiden Twin Crown", ArmorLocation.Base),
        new(294000, "Nox Swordstress Crown (Altered)", ArmorLocation.Base),
        new(300000, "Great Horned Headband", ArmorLocation.Base),
        new(301000, "Shining Horned Headband", ArmorLocation.Base),
        new(310000, "Duelist Helm", ArmorLocation.Base),
        new(320000, "Sanguine Noble Hood", ArmorLocation.Base),
        new(330000, "Guardian Mask", ArmorLocation.Base),
        new(340000, "Cleanrot Helm", ArmorLocation.Base),
        new(341000, "Cleanrot Helm (Altered)", ArmorLocation.Base),
        new(350000, "Fire Monk Hood", ArmorLocation.Base),
        new(351000, "Blackflame Monk Hood", ArmorLocation.Base),
        new(360000, "Fire Prelate Helm", ArmorLocation.Base),
        new(370000, "Aristocrat Headband", ArmorLocation.Base),
        new(380000, "Aristocrat Hat", ArmorLocation.Base),
        new(390000, "Old Aristocrat Cowl", ArmorLocation.Base),
        new(420000, "Vulgar Militia Helm", ArmorLocation.Base),
        new(430000, "Sage Hood", ArmorLocation.Base),
        new(440000, "Pumpkin Helm", ArmorLocation.Base),
        new(460000, "Elden Lord Crown", ArmorLocation.Base),
        new(470000, "Radahn's Redmane Helm", ArmorLocation.Base),
        new(510000, "Queen's Crescent Crown", ArmorLocation.Base),
        new(520000, "Godskin Apostle Hood", ArmorLocation.Base),
        new(530000, "Godskin Noble Hood", ArmorLocation.Base),
        new(540000, "Depraved Perfumer Headscarf", ArmorLocation.Base),
        new(570000, "Crucible Axe Helm", ArmorLocation.Base),
        new(571000, "Crucible Tree Helm", ArmorLocation.Base),
        new(580000, "Lusat's Glintstone Crown", ArmorLocation.Base),
        new(581000, "Azur's Glintstone Crown", ArmorLocation.Base),
        new(590000, "All-Knowing Helm", ArmorLocation.Base),
        new(600000, "Twinned Helm", ArmorLocation.Base),
        new(620000, "Prophet Blindfold", ArmorLocation.Base),
        new(630000, "Astrologer Hood", ArmorLocation.Base),
        new(640000, "Lionel's Helm", ArmorLocation.Base),
        new(650000, "Hoslow's Helm", ArmorLocation.Base),
        new(651000, "Diallos's Mask", ArmorLocation.Base),
        new(660000, "Vagabond Knight Helm", ArmorLocation.Base),
        new(670000, "Blue Cloth Cowl", ArmorLocation.Base),
        new(680000, "White Mask", ArmorLocation.Base),
        new(690000, "Royal Remains Helm", ArmorLocation.Base),
        new(720000, "Beast Champion Helm", ArmorLocation.Base),
        new(730000, "Champion Headband", ArmorLocation.Base),
        new(740000, "Crimson Hood", ArmorLocation.Base),
        new(741000, "Navy Hood", ArmorLocation.Base),
        new(760000, "Maliketh's Helm", ArmorLocation.Base),
        new(770000, "Malenia's Winged Helm", ArmorLocation.Base),
        new(780000, "Veteran's Helm", ArmorLocation.Base),
        new(790000, "Bloodhound Knight Helm", ArmorLocation.Base),
        new(800000, "Festive Hood", ArmorLocation.Base),
        new(801000, "Festive Hood (Altered)", ArmorLocation.Base),
        new(802000, "Blue Festive Hood", ArmorLocation.Base),
        new(810000, "Commoner's Headband", ArmorLocation.Base),
        new(811000, "Commoner's Headband (Altered)", ArmorLocation.Base),
        new(820000, "Envoy Crown", ArmorLocation.Base),
        new(830000, "Twinsage Glintstone Crown", ArmorLocation.Base),
        new(831000, "Olivinus Glintstone Crown", ArmorLocation.Base),
        new(832000, "Lazuli Glintstone Crown", ArmorLocation.Base),
        new(833000, "Karolos Glintstone Crown", ArmorLocation.Base),
        new(834000, "Witch's Glintstone Crown", ArmorLocation.Base),
        new(840000, "Marionette Soldier Helm", ArmorLocation.Base),
        new(850000, "Marionette Soldier Birdhelm", ArmorLocation.Base),
        new(860000, "Raging Wolf Helm", ArmorLocation.Base),
        new(870000, "Land of Reeds Helm", ArmorLocation.Base),
        new(872000, "Okina Mask", ArmorLocation.Base),
        new(880000, "Confessor Hood", ArmorLocation.Base),
        new(881000, "Confessor Hood (Altered)", ArmorLocation.Base),
        new(890000, "Prisoner Iron Mask", ArmorLocation.Base),
        new(891000, "Blackguard's Iron Mask", ArmorLocation.Base),
        new(900000, "Traveling Maiden Hood", ArmorLocation.Base),
        new(902000, "Finger Maiden Fillet", ArmorLocation.Base),
        new(910000, "Preceptor's Big Hat", ArmorLocation.Base),
        new(911000, "Mask of Confidence", ArmorLocation.Base),
        new(930000, "Skeletal Mask", ArmorLocation.Base),
        new(940000, "Eccentric's Hood", ArmorLocation.Base),
        new(941000, "Eccentric's Hood (Altered)", ArmorLocation.Base),
        new(950000, "Fingerprint Helm", ArmorLocation.Base),
        new(960000, "Consort's Mask", ArmorLocation.Base),
        new(961000, "Ruler's Mask", ArmorLocation.Base),
        new(963000, "Marais Mask", ArmorLocation.Base),
        new(964000, "Bloodsoaked Mask", ArmorLocation.Base),
        new(970000, "Omen Helm", ArmorLocation.Base),
        new(980000, "Carian Knight Helm", ArmorLocation.Base),
        new(990000, "Hierodas Glintstone Crown", ArmorLocation.Base),
        new(1000000, "Haima Glintstone Crown", ArmorLocation.Base),
        new(1010000, "Snow Witch Hat", ArmorLocation.Base),
        new(1030000, "Juvenile Scholar Cap", ArmorLocation.Base),
        new(1040000, "Radiant Gold Mask", ArmorLocation.Base),
        new(1060000, "Albinauric Mask", ArmorLocation.Base),
        new(1070000, "Zamor Mask", ArmorLocation.Base),
        new(1080000, "Imp Head (Cat)", ArmorLocation.Base),
        new(1081000, "Imp Head (Fanged)", ArmorLocation.Base),
        new(1082000, "Imp Head (Long-Tongued)", ArmorLocation.Base),
        new(1083000, "Imp Head (Corpse)", ArmorLocation.Base),
        new(1084000, "Imp Head (Wolf)", ArmorLocation.Base),
        new(1085000, "Imp Head (Elder)", ArmorLocation.Base),
        new(1090000, "Silver Tear Mask", ArmorLocation.Base),
        new(1100000, "Chain Coif", ArmorLocation.Base),
        new(1101000, "Greathelm", ArmorLocation.Base),
        new(1110000, "Octopus Head", ArmorLocation.Base),
        new(1120000, "Jar", ArmorLocation.Base),
        new(1130000, "Mushroom Head", ArmorLocation.Base),
        new(1300000, "Nox Mirrorhelm", ArmorLocation.Base),
        new(1301000, "Iji's Mirrorhelm", ArmorLocation.Base),
        new(1400000, "Black Hood", ArmorLocation.Base),
        new(1401000, "Bandit Mask", ArmorLocation.Base),
        new(1500000, "Knight Helm", ArmorLocation.Base),
        new(1600000, "Greathood", ArmorLocation.Base),
        new(1700000, "Godrick Soldier Helm", ArmorLocation.Base),
        new(1710000, "Raya Lucarian Helm", ArmorLocation.Base),
        new(1720000, "Leyndell Soldier Helm", ArmorLocation.Base),
        new(1730000, "Radahn Soldier Helm", ArmorLocation.Base),
        new(1750000, "Haligtree Helm", ArmorLocation.Base),
        new(1760000, "Gelmir Knight Helm", ArmorLocation.Base),
        new(1770000, "Godrick Knight Helm", ArmorLocation.Base),
        new(1780000, "Cuckoo Knight Helm", ArmorLocation.Base),
        new(1790000, "Leyndell Knight Helm", ArmorLocation.Base),
        new(1800000, "Redmane Knight Helm", ArmorLocation.Base),
        new(1820000, "Haligtree Knight Helm", ArmorLocation.Base),
        new(1830000, "Foot Soldier Cap", ArmorLocation.Base),
        new(1840000, "Foot Soldier Helmet", ArmorLocation.Base),
        new(1850000, "Gilded Foot Soldier Cap", ArmorLocation.Base),
        new(1860000, "Foot Soldier Helm", ArmorLocation.Base),
        new(1880000, "Sacred Crown Helm", ArmorLocation.Base),
        new(1890000, "Omensmirk Mask", ArmorLocation.Base),
        new(1900000, "Ash-of-War Scarab", ArmorLocation.Base),
        new(1901000, "Incantation Scarab", ArmorLocation.Base),
        new(1902000, "Glintstone Scarab", ArmorLocation.Base),
        new(1910000, "Crimson Tear Scarab", ArmorLocation.Base),
        new(1920000, "Cerulean Tear Scarab", ArmorLocation.Base),
        new(1940000, "Fia's Hood", ArmorLocation.Base),
        new(1980000, "Highwayman Hood", ArmorLocation.Base),
        new(1990000, "High Page Hood", ArmorLocation.Base),
        new(2000000, "Rotten Duelist Helm", ArmorLocation.Base),
        new(2010000, "Mushroom Crown", ArmorLocation.Base),
        new(2020000, "Black Dumpling", ArmorLocation.Base),
        new(3000000, "Dane's Hat", ArmorLocation.Dlc),
        new(3010000, "Gaius's Helm", ArmorLocation.Dlc),
        new(5000000, "Oathseeker Knight Helm", ArmorLocation.Dlc),
        new(5010000, "Verdigris Helm", ArmorLocation.Dlc),
        new(5020000, "Pelt of Ralva", ArmorLocation.Dlc),
        new(5021000, "Fang Helm", ArmorLocation.Dlc),
        new(5030000, "Thiollier's Mask", ArmorLocation.Dlc),
        new(5060000, "High Priest Hat", ArmorLocation.Dlc),
        new(5070000, "Caterpillar Mask", ArmorLocation.Dlc),
        new(5080000, "Dancer's Hood", ArmorLocation.Dlc),
        new(5090000, "Helm of Night", ArmorLocation.Dlc),
        new(5100000, "Igon's Helm", ArmorLocation.Dlc),
        new(5101000, "Igon's Helm (Altered)", ArmorLocation.Dlc),
        new(5110000, "Wise Man's Mask", ArmorLocation.Dlc),
        new(5120000, "Freyja's Helm", ArmorLocation.Dlc),
        new(5130000, "Helm of Solitude", ArmorLocation.Dlc),
        new(5140000, "Messmer Soldier Helm", ArmorLocation.Dlc),
        new(5150000, "Black Knight Helm", ArmorLocation.Dlc),
        new(5160000, "Rakshasa Helm", ArmorLocation.Dlc),
        new(5180000, "Fire Knight Helm", ArmorLocation.Dlc),
        new(5182000, "Death Mask Helm", ArmorLocation.Dlc),
        new(5183000, "Winged Serpent Helm", ArmorLocation.Dlc),
        new(5184000, "Salza's Hood", ArmorLocation.Dlc),
        new(5190000, "Leather Headband", ArmorLocation.Dlc),
        new(5191000, "Leather Crown", ArmorLocation.Dlc),
        new(5200000, "Death Knight Helm", ArmorLocation.Dlc),
        new(5210000, "Curseblade Mask", ArmorLocation.Dlc),
        new(5220000, "Messmer's Helm", ArmorLocation.Dlc),
        new(5221000, "Messmer's Helm (Altered)", ArmorLocation.Dlc),
        new(5230000, "Gravebird Helm", ArmorLocation.Dlc),
        new(5240000, "Common Soldier Helm", ArmorLocation.Dlc),
        new(5250000, "Horned Warrior Helm", ArmorLocation.Dlc),
        new(5252000, "Divine Beast Helm", ArmorLocation.Dlc),
        new(5253000, "Divine Bird Helm", ArmorLocation.Dlc),
        new(5260000, "Rellana's Helm", ArmorLocation.Dlc),
        new(5270000, "Young Lion's Helm", ArmorLocation.Dlc),
        new(5272000, "Circlet of Light", ArmorLocation.Dlc),
        new(5280000, "Shadow Militiaman Helm", ArmorLocation.Dlc),
        new(5290000, "Divine Beast Head", ArmorLocation.Dlc),
        new(5300000, "St. Trina's Blossom", ArmorLocation.Dlc),
        new(5310000, "Crucible Hammer-Helm", ArmorLocation.Dlc),
        new(5320000, "Greatjar", ArmorLocation.Dlc),
        new(5330000, "Imp Head (Lion)", ArmorLocation.Dlc),
    };
}

public static class ChestArmor
{
    public static readonly ArmorEntry[] All =
    {
        new(40100, "Scale Armor", ArmorLocation.Base),
        new(50100, "Kaiden Armor", ArmorLocation.Base),
        new(60100, "Drake Knight Armor", ArmorLocation.Base),
        new(61100, "Drake Knight Armor (Altered)", ArmorLocation.Base),
        new(80100, "Scaled Armor", ArmorLocation.Base),
        new(81100, "Scaled Armor (Altered)", ArmorLocation.Base),
        new(90100, "Perfumer Robe", ArmorLocation.Base),
        new(91100, "Perfumer Robe (Altered)", ArmorLocation.Base),
        new(100100, "Perfumer's Traveling Garb", ArmorLocation.Base),
        new(101100, "Perfumer's Traveling Garb (Altered)", ArmorLocation.Base),
        new(120100, "Alberich's Robe", ArmorLocation.Base),
        new(121100, "Alberich's Robe (Altered)", ArmorLocation.Base),
        new(130100, "Spellblade's Traveling Attire", ArmorLocation.Base),
        new(131100, "Spellblade's Traveling Attire (Altered)", ArmorLocation.Base),
        new(140100, "Bull-Goat Armor", ArmorLocation.Base),
        new(150100, "Ronin's Armor", ArmorLocation.Base),
        new(151100, "Ronin's Armor (Altered)", ArmorLocation.Base),
        new(160100, "Cloth Garb", ArmorLocation.Base),
        new(170100, "Blaidd's Armor", ArmorLocation.Base),
        new(171100, "Blaidd's Armor (Altered)", ArmorLocation.Base),
        new(180100, "Black Knife Armor", ArmorLocation.Base),
        new(181100, "Black Knife Armor (Altered)", ArmorLocation.Base),
        new(190100, "Exile Armor", ArmorLocation.Base),
        new(200100, "Banished Knight Armor", ArmorLocation.Base),
        new(201100, "Banished Knight Armor (Altered)", ArmorLocation.Base),
        new(210100, "Briar Armor", ArmorLocation.Base),
        new(211100, "Briar Armor (Altered)", ArmorLocation.Base),
        new(220100, "Page Garb", ArmorLocation.Base),
        new(221100, "Page Garb (Altered)", ArmorLocation.Base),
        new(230100, "Night's Cavalry Armor", ArmorLocation.Base),
        new(231100, "Night's Cavalry Armor (Altered)", ArmorLocation.Base),
        new(240100, "Blue Silver Mail Armor", ArmorLocation.Base),
        new(241100, "Blue Silver Mail Armor (Altered)", ArmorLocation.Base),
        new(250100, "Nomadic Merchant's Finery", ArmorLocation.Base),
        new(251100, "Nomadic Merchant's Finery (Altered)", ArmorLocation.Base),
        new(260100, "Malformed Dragon Armor", ArmorLocation.Base),
        new(270100, "Tree Sentinel Armor", ArmorLocation.Base),
        new(271100, "Tree Sentinel Armor (Altered)", ArmorLocation.Base),
        new(280100, "Royal Knight Armor", ArmorLocation.Base),
        new(281100, "Royal Knight Armor (Altered)", ArmorLocation.Base),
        new(290100, "Nox Monk Armor", ArmorLocation.Base),
        new(291100, "Nox Monk Armor (Altered)", ArmorLocation.Base),
        new(292100, "Nox Swordstress Armor", ArmorLocation.Base),
        new(293100, "Night Maiden Armor", ArmorLocation.Base),
        new(294100, "Nox Swordstress Armor (Altered)", ArmorLocation.Base),
        new(300100, "Fur Raiment", ArmorLocation.Base),
        new(301100, "Shaman Furs", ArmorLocation.Base),
        new(310100, "Gravekeeper Cloak", ArmorLocation.Base),
        new(311100, "Gravekeeper Cloak (Altered)", ArmorLocation.Base),
        new(320100, "Sanguine Noble Robe", ArmorLocation.Base),
        new(330100, "Guardian Garb (Full Bloom)", ArmorLocation.Base),
        new(331100, "Guardian Garb", ArmorLocation.Base),
        new(340100, "Cleanrot Armor", ArmorLocation.Base),
        new(341100, "Cleanrot Armor (Altered)", ArmorLocation.Base),
        new(350100, "Fire Monk Armor", ArmorLocation.Base),
        new(351100, "Blackflame Monk Armor", ArmorLocation.Base),
        new(360100, "Fire Prelate Armor", ArmorLocation.Base),
        new(361100, "Fire Prelate Armor (Altered)", ArmorLocation.Base),
        new(370100, "Aristocrat Garb", ArmorLocation.Base),
        new(371100, "Aristocrat Garb (Altered)", ArmorLocation.Base),
        new(380100, "Aristocrat Coat", ArmorLocation.Base),
        new(390100, "Old Aristocrat Gown", ArmorLocation.Base),
        new(420100, "Vulgar Militia Armor", ArmorLocation.Base),
        new(430100, "Sage Robe", ArmorLocation.Base),
        new(460100, "Elden Lord Armor", ArmorLocation.Base),
        new(461100, "Elden Lord Armor (Altered)", ArmorLocation.Base),
        new(470100, "Radahn's Lion Armor", ArmorLocation.Base),
        new(471100, "Radahn's Lion Armor (Altered)", ArmorLocation.Base),
        new(480100, "Lord of Blood's Robe", ArmorLocation.Base),
        new(481100, "Lord of Blood's Robe (Altered)", ArmorLocation.Base),
        new(510100, "Queen's Robe", ArmorLocation.Base),
        new(520100, "Godskin Apostle Robe", ArmorLocation.Base),
        new(530100, "Godskin Noble Robe", ArmorLocation.Base),
        new(540100, "Depraved Perfumer Robe", ArmorLocation.Base),
        new(541100, "Depraved Perfumer Robe (Altered)", ArmorLocation.Base),
        new(570100, "Crucible Axe Armor", ArmorLocation.Base),
        new(571100, "Crucible Tree Armor", ArmorLocation.Base),
        new(572100, "Crucible Axe Armor (Altered)", ArmorLocation.Base),
        new(573100, "Crucible Tree Armor (Altered)", ArmorLocation.Base),
        new(580100, "Lusat's Robe", ArmorLocation.Base),
        new(581100, "Azur's Glintstone Robe", ArmorLocation.Base),
        new(590100, "All-Knowing Armor", ArmorLocation.Base),
        new(591100, "All-Knowing Armor (Altered)", ArmorLocation.Base),
        new(600100, "Twinned Armor", ArmorLocation.Base),
        new(601100, "Twinned Armor (Altered)", ArmorLocation.Base),
        new(620100, "Corhyn's Robe", ArmorLocation.Base),
        new(621100, "Prophet Robe (Altered)", ArmorLocation.Base),
        new(622100, "Prophet Robe", ArmorLocation.Base),
        new(630100, "Astrologer Robe", ArmorLocation.Base),
        new(631100, "Astrologer Robe (Altered)", ArmorLocation.Base),
        new(640100, "Lionel's Armor", ArmorLocation.Base),
        new(641100, "Lionel's Armor (Altered)", ArmorLocation.Base),
        new(650100, "Hoslow's Armor", ArmorLocation.Base),
        new(652100, "Hoslow's Armor (Altered)", ArmorLocation.Base),
        new(660100, "Vagabond Knight Armor", ArmorLocation.Base),
        new(661100, "Vagabond Knight Armor (Altered)", ArmorLocation.Base),
        new(670100, "Blue Cloth Vest", ArmorLocation.Base),
        new(680100, "War Surgeon Gown", ArmorLocation.Base),
        new(681100, "War Surgeon Gown (Altered)", ArmorLocation.Base),
        new(690100, "Royal Remains Armor", ArmorLocation.Base),
        new(720100, "Beast Champion Armor", ArmorLocation.Base),
        new(721100, "Beast Champion Armor (Altered)", ArmorLocation.Base),
        new(730100, "Champion Pauldron", ArmorLocation.Base),
        new(740100, "Noble's Traveling Garb", ArmorLocation.Base),
        new(760100, "Maliketh's Armor", ArmorLocation.Base),
        new(761100, "Maliketh's Armor (Altered)", ArmorLocation.Base),
        new(770100, "Malenia's Armor", ArmorLocation.Base),
        new(771100, "Malenia's Armor (Altered)", ArmorLocation.Base),
        new(780100, "Veteran's Armor", ArmorLocation.Base),
        new(781100, "Veteran's Armor (Altered)", ArmorLocation.Base),
        new(790100, "Bloodhound Knight Armor", ArmorLocation.Base),
        new(791100, "Bloodhound Knight Armor (Altered)", ArmorLocation.Base),
        new(800100, "Festive Garb", ArmorLocation.Base),
        new(801100, "Festive Garb (Altered)", ArmorLocation.Base),
        new(802100, "Blue Festive Garb", ArmorLocation.Base),
        new(810100, "Commoner's Garb", ArmorLocation.Base),
        new(811100, "Commoner's Garb (Altered)", ArmorLocation.Base),
        new(812000, "Commoner's Simple Garb", ArmorLocation.Base),
        new(812100, "Commoner's Simple Garb (Altered)", ArmorLocation.Base),
        new(830100, "Raya Lucarian Robe", ArmorLocation.Base),
        new(840100, "Marionette Soldier Armor", ArmorLocation.Base),
        new(860100, "Raging Wolf Armor", ArmorLocation.Base),
        new(861100, "Raging Wolf Armor (Altered)", ArmorLocation.Base),
        new(870100, "Land of Reeds Armor", ArmorLocation.Base),
        new(871100, "Land of Reeds Armor (Altered)", ArmorLocation.Base),
        new(872100, "White Reed Armor", ArmorLocation.Base),
        new(880100, "Confessor Armor", ArmorLocation.Base),
        new(881100, "Confessor Armor (Altered)", ArmorLocation.Base),
        new(890100, "Prisoner Clothing", ArmorLocation.Base),
        new(900100, "Traveling Maiden Robe", ArmorLocation.Base),
        new(901100, "Traveling Maiden Robe (Altered)", ArmorLocation.Base),
        new(902100, "Finger Maiden Robe", ArmorLocation.Base),
        new(903100, "Finger Maiden Robe (Altered)", ArmorLocation.Base),
        new(910100, "Preceptor's Long Gown", ArmorLocation.Base),
        new(911100, "Preceptor's Long Gown (Altered)", ArmorLocation.Base),
        new(930100, "Raptor's Black Feathers", ArmorLocation.Base),
        new(931100, "Bandit Garb", ArmorLocation.Base),
        new(940100, "Eccentric's Armor", ArmorLocation.Base),
        new(950100, "Fingerprint Armor", ArmorLocation.Base),
        new(951100, "Fingerprint Armor (Altered)", ArmorLocation.Base),
        new(960100, "Consort's Robe", ArmorLocation.Base),
        new(961100, "Ruler's Robe", ArmorLocation.Base),
        new(962100, "Upper-Class Robe", ArmorLocation.Base),
        new(963100, "Marais Robe", ArmorLocation.Base),
        new(964100, "Official's Attire", ArmorLocation.Base),
        new(970100, "Omen Armor", ArmorLocation.Base),
        new(980100, "Carian Knight Armor", ArmorLocation.Base),
        new(981100, "Carian Knight Armor (Altered)", ArmorLocation.Base),
        new(990100, "Errant Sorcerer Robe", ArmorLocation.Base),
        new(991100, "Errant Sorcerer Robe (Altered)", ArmorLocation.Base),
        new(1000100, "Battlemage Robe", ArmorLocation.Base),
        new(1010100, "Snow Witch Robe", ArmorLocation.Base),
        new(1011100, "Snow Witch Robe (Altered)", ArmorLocation.Base),
        new(1020100, "Traveler's Clothes", ArmorLocation.Base),
        new(1030100, "Juvenile Scholar Robe", ArmorLocation.Base),
        new(1040100, "Goldmask's Rags", ArmorLocation.Base),
        new(1050100, "Fell Omen Cloak", ArmorLocation.Base),
        new(1060100, "Dirty Chainmail", ArmorLocation.Base),
        new(1070100, "Zamor Armor", ArmorLocation.Base),
        new(1100100, "Chain Armor", ArmorLocation.Base),
        new(1101100, "Eye Surcoat", ArmorLocation.Base),
        new(1102100, "Tree Surcoat", ArmorLocation.Base),
        new(1130100, "Mushroom Body", ArmorLocation.Base),
        new(1400100, "Leather Armor", ArmorLocation.Base),
        new(1500100, "Knight Armor", ArmorLocation.Base),
        new(1700100, "Tree-and-Beast Surcoat", ArmorLocation.Base),
        new(1710100, "Cuckoo Surcoat", ArmorLocation.Base),
        new(1720100, "Erdtree Surcoat", ArmorLocation.Base),
        new(1730100, "Redmane Surcoat", ArmorLocation.Base),
        new(1740100, "Mausoleum Surcoat", ArmorLocation.Base),
        new(1750100, "Haligtree Crest Surcoat", ArmorLocation.Base),
        new(1760100, "Gelmir Knight Armor", ArmorLocation.Base),
        new(1761100, "Gelmir Knight Armor (Altered)", ArmorLocation.Base),
        new(1770100, "Godrick Knight Armor", ArmorLocation.Base),
        new(1771100, "Godrick Knight Armor (Altered)", ArmorLocation.Base),
        new(1780100, "Cuckoo Knight Armor", ArmorLocation.Base),
        new(1781100, "Cuckoo Knight Armor (Altered)", ArmorLocation.Base),
        new(1790100, "Leyndell Knight Armor", ArmorLocation.Base),
        new(1791100, "Leyndell Knight Armor (Altered)", ArmorLocation.Base),
        new(1800100, "Redmane Knight Armor", ArmorLocation.Base),
        new(1801100, "Redmane Knight Armor (Altered)", ArmorLocation.Base),
        new(1810100, "Mausoleum Knight Armor", ArmorLocation.Base),
        new(1811100, "Mausoleum Knight Armor (Altered)", ArmorLocation.Base),
        new(1820100, "Haligtree Knight Armor", ArmorLocation.Base),
        new(1821100, "Haligtree Knight Armor (Altered)", ArmorLocation.Base),
        new(1830100, "Chain-Draped Tabard", ArmorLocation.Base),
        new(1840100, "Foot Soldier Tabard", ArmorLocation.Base),
        new(1850100, "Leather-Draped Tabard", ArmorLocation.Base),
        new(1860100, "Scarlet Tabard", ArmorLocation.Base),
        new(1870100, "Bloodsoaked Tabard", ArmorLocation.Base),
        new(1880100, "Ivory-Draped Tabard", ArmorLocation.Base),
        new(1890100, "Omenkiller Robe", ArmorLocation.Base),
        new(1930100, "Deathbed Dress", ArmorLocation.Base),
        new(1940100, "Fia's Robe", ArmorLocation.Base),
        new(1941100, "Fia's Robe (Altered)", ArmorLocation.Base),
        new(1980100, "Highwayman Cloth Armor", ArmorLocation.Base),
        new(1990100, "High Page Clothes", ArmorLocation.Base),
        new(1991100, "High Page Clothes (Altered)", ArmorLocation.Base),
        new(2000100, "Rotten Gravekeeper Cloak", ArmorLocation.Base),
        new(2001100, "Rotten Gravekeeper Cloak (Altered)", ArmorLocation.Base),
        new(2030000, "Lazuli Robe", ArmorLocation.Base),
        new(3000100, "Dryleaf Robe", ArmorLocation.Dlc),
        new(3001100, "Dryleaf Robe (Altered)", ArmorLocation.Dlc),
        new(3010100, "Gaius's Armor", ArmorLocation.Dlc),
        new(5000100, "Leda's Armor", ArmorLocation.Dlc),
        new(5002100, "Oathseeker Knight Armor", ArmorLocation.Dlc),
        new(5010100, "Verdigris Armor", ArmorLocation.Dlc),
        new(5020100, "Iron Rivet Armor", ArmorLocation.Dlc),
        new(5030100, "Thiollier's Garb", ArmorLocation.Dlc),
        new(5031100, "Thiollier's Garb (Altered)", ArmorLocation.Dlc),
        new(5060100, "High Priest Robe", ArmorLocation.Dlc),
        new(5062100, "Finger Robe", ArmorLocation.Dlc),
        new(5070100, "Braided Cord Robe", ArmorLocation.Dlc),
        new(5080100, "Dancer's Dress", ArmorLocation.Dlc),
        new(5081100, "Dancer's Dress (Altered)", ArmorLocation.Dlc),
        new(5090100, "Armor of Night", ArmorLocation.Dlc),
        new(5100100, "Igon's Armor", ArmorLocation.Dlc),
        new(5101100, "Igon's Armor (Altered)", ArmorLocation.Dlc),
        new(5110100, "Ansbach's Attire", ArmorLocation.Dlc),
        new(5111100, "Ansbach's Attire (Altered)", ArmorLocation.Dlc),
        new(5120100, "Freyja's Armor", ArmorLocation.Dlc),
        new(5121100, "Freyja's Armor (Altered)", ArmorLocation.Dlc),
        new(5130100, "Armor of Solitude", ArmorLocation.Dlc),
        new(5131100, "Armor of Solitude (Altered)", ArmorLocation.Dlc),
        new(5140100, "Messmer Soldier Armor", ArmorLocation.Dlc),
        new(5141100, "Messmer Soldier Armor (Altered)", ArmorLocation.Dlc),
        new(5150100, "Black Knight Armor", ArmorLocation.Dlc),
        new(5160100, "Rakshasa Armor", ArmorLocation.Dlc),
        new(5180100, "Fire Knight Armor", ArmorLocation.Dlc),
        new(5181100, "Fire Knight Armor (Altered)", ArmorLocation.Dlc),
        new(5190100, "Gloried Attire", ArmorLocation.Dlc),
        new(5191100, "Highland Attire", ArmorLocation.Dlc),
        new(5200100, "Death Knight Armor", ArmorLocation.Dlc),
        new(5210100, "Ascetic's Loincloth", ArmorLocation.Dlc),
        new(5220100, "Messmer's Armor", ArmorLocation.Dlc),
        new(5230100, "Gravebird's Blackquill Armor", ArmorLocation.Dlc),
        new(5231100, "Gravebird Armor", ArmorLocation.Dlc),
        new(5240100, "Common Soldier Cloth Armor", ArmorLocation.Dlc),
        new(5250100, "Horned Warrior Armor", ArmorLocation.Dlc),
        new(5252100, "Divine Beast Warrior Armor", ArmorLocation.Dlc),
        new(5253100, "Divine Bird Warrior Armor", ArmorLocation.Dlc),
        new(5260100, "Rellana's Armor", ArmorLocation.Dlc),
        new(5270100, "Young Lion's Armor", ArmorLocation.Dlc),
        new(5271100, "Young Lion's Armor (Altered)", ArmorLocation.Dlc),
        new(5280100, "Shadow Militiaman Armor", ArmorLocation.Dlc),
    };
}
