namespace Hades.Constants;

public enum SpellType
{
    Sorcery,
    Incantation,
    DragonCommunion,
}

public enum SpellLocation
{
    Base,
    Dlc,
}

public readonly record struct SpellEntry(
    int Id,
    string Name,
    SpellType Type,
    SpellLocation Location,
    byte EquipType = 3,
    int Category = 1
);

public static class Spells
{
    public static readonly SpellEntry[] Sorceries =
    {
        new(4000, "Glintstone Pebble", SpellType.Sorcery, SpellLocation.Base),
        new(4001, "Great Glintstone Shard", SpellType.Sorcery, SpellLocation.Base),
        new(4010, "Swift Glintstone Shard", SpellType.Sorcery, SpellLocation.Base),
        new(4020, "Glintstone Cometshard", SpellType.Sorcery, SpellLocation.Base),
        new(4021, "Comet", SpellType.Sorcery, SpellLocation.Base),
        new(4030, "Shard Spiral", SpellType.Sorcery, SpellLocation.Base),
        new(4040, "Glintstone Stars", SpellType.Sorcery, SpellLocation.Base),
        new(4050, "Star Shower", SpellType.Sorcery, SpellLocation.Base),
        new(4060, "Crystal Barrage", SpellType.Sorcery, SpellLocation.Base),
        new(4070, "Glintstone Arc", SpellType.Sorcery, SpellLocation.Base),
        new(4080, "Cannon of Haima", SpellType.Sorcery, SpellLocation.Base),
        new(4090, "Crystal Burst", SpellType.Sorcery, SpellLocation.Base),
        new(4100, "Shatter Earth", SpellType.Sorcery, SpellLocation.Base),
        new(4110, "Rock Blaster", SpellType.Sorcery, SpellLocation.Base),
        new(4120, "Gavel of Haima", SpellType.Sorcery, SpellLocation.Base),
        new(4130, "Terra Magica", SpellType.Sorcery, SpellLocation.Base),
        new(4140, "Starlight", SpellType.Sorcery, SpellLocation.Base),
        new(4200, "Comet Azur", SpellType.Sorcery, SpellLocation.Base),
        new(4210, "Founding Rain of Stars", SpellType.Sorcery, SpellLocation.Base),
        new(4220, "Stars of Ruin", SpellType.Sorcery, SpellLocation.Base),
        new(4300, "Glintblade Phalanx", SpellType.Sorcery, SpellLocation.Base),
        new(4301, "Carian Phalanx", SpellType.Sorcery, SpellLocation.Base),
        new(4302, "Greatblade Phalanx", SpellType.Sorcery, SpellLocation.Base),
        new(4360, "Rennala's Full Moon", SpellType.Sorcery, SpellLocation.Base),
        new(4361, "Ranni's Dark Moon", SpellType.Sorcery, SpellLocation.Base),
        new(4370, "Magic Downpour", SpellType.Sorcery, SpellLocation.Base),
        new(4380, "Loretta's Greatbow", SpellType.Sorcery, SpellLocation.Base),
        new(4381, "Loretta's Mastery", SpellType.Sorcery, SpellLocation.Base),
        new(4390, "Magic Glintblade", SpellType.Sorcery, SpellLocation.Base),
        new(4400, "Glintstone Icecrag", SpellType.Sorcery, SpellLocation.Base),
        new(4410, "Zamor Ice Storm", SpellType.Sorcery, SpellLocation.Base),
        new(4420, "Freezing Mist", SpellType.Sorcery, SpellLocation.Base),
        new(4430, "Carian Greatsword", SpellType.Sorcery, SpellLocation.Base),
        new(4431, "Adula's Moonblade", SpellType.Sorcery, SpellLocation.Base),
        new(4440, "Carian Slicer", SpellType.Sorcery, SpellLocation.Base),
        new(4450, "Carian Piercer", SpellType.Sorcery, SpellLocation.Base),
        new(4460, "Scholar's Armament", SpellType.Sorcery, SpellLocation.Base),
        new(4470, "Scholar's Shield", SpellType.Sorcery, SpellLocation.Base),
        new(4480, "Lucidity", SpellType.Sorcery, SpellLocation.Base),
        new(4490, "Frozen Armament", SpellType.Sorcery, SpellLocation.Base),
        new(4500, "Shattering Crystal", SpellType.Sorcery, SpellLocation.Base),
        new(4510, "Crystal Release", SpellType.Sorcery, SpellLocation.Base),
        new(4520, "Crystal Torrent", SpellType.Sorcery, SpellLocation.Base),
        new(4600, "Ambush Shard", SpellType.Sorcery, SpellLocation.Base),
        new(4610, "Night Shard", SpellType.Sorcery, SpellLocation.Base),
        new(4620, "Night Comet", SpellType.Sorcery, SpellLocation.Base),
        new(4630, "Thops's Barrier", SpellType.Sorcery, SpellLocation.Base),
        new(4640, "Carian Retaliation", SpellType.Sorcery, SpellLocation.Base),
        new(4650, "Eternal Darkness", SpellType.Sorcery, SpellLocation.Base),
        new(4660, "Unseen Blade", SpellType.Sorcery, SpellLocation.Base),
        new(4670, "Unseen Form", SpellType.Sorcery, SpellLocation.Base),
        new(4700, "Meteorite", SpellType.Sorcery, SpellLocation.Base),
        new(4701, "Meteorite of Astel", SpellType.Sorcery, SpellLocation.Base),
        new(4710, "Rock Sling", SpellType.Sorcery, SpellLocation.Base),
        new(4720, "Gravity Well", SpellType.Sorcery, SpellLocation.Base),
        new(4721, "Collapsing Stars", SpellType.Sorcery, SpellLocation.Base),
        new(4800, "Magma Shot", SpellType.Sorcery, SpellLocation.Base),
        new(4810, "Gelmir's Fury", SpellType.Sorcery, SpellLocation.Base),
        new(4820, "Roiling Magma", SpellType.Sorcery, SpellLocation.Base),
        new(4830, "Rykard's Rancor", SpellType.Sorcery, SpellLocation.Base),
        new(4900, "Briars of Sin", SpellType.Sorcery, SpellLocation.Base),
        new(4910, "Briars of Punishment", SpellType.Sorcery, SpellLocation.Base),
        new(5000, "Rancorcall", SpellType.Sorcery, SpellLocation.Base),
        new(5001, "Ancient Death Rancor", SpellType.Sorcery, SpellLocation.Base),
        new(5010, "Explosive Ghostflame", SpellType.Sorcery, SpellLocation.Base),
        new(5020, "Fia's Mist", SpellType.Sorcery, SpellLocation.Base),
        new(5030, "Tibia's Summons", SpellType.Sorcery, SpellLocation.Base),
        new(5100, "Oracle Bubbles", SpellType.Sorcery, SpellLocation.Base),
        new(5110, "Great Oracular Bubble", SpellType.Sorcery, SpellLocation.Base),
        new(6500, "Night Maiden's Mist", SpellType.Sorcery, SpellLocation.Base),
        new(2004300, "Miriam's Vanishing", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004310, "Glintblade Trio", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004320, "Rellana's Twin Moons", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004500, "Glintstone Nail", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004510, "Glintstone Nails", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004700, "Blades of Stone", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004710, "Gravitational Missile", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004900, "Mantle of Thorns", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004910, "Impenetrable Thorns", SpellType.Sorcery, SpellLocation.Dlc),
        new(2005000, "Rings of Spectral Light", SpellType.Sorcery, SpellLocation.Dlc),
        new(2006200, "Vortex of Putrescence", SpellType.Sorcery, SpellLocation.Dlc),
        new(2006210, "Mass of Putrescence", SpellType.Sorcery, SpellLocation.Dlc),
        new(2007410, "Fleeting Microcosm", SpellType.Sorcery, SpellLocation.Dlc),
        new(2007420, "Cherishing Fingers", SpellType.Sorcery, SpellLocation.Dlc),
    };

    public static readonly SpellEntry[] Incantations =
    {
        new(5040, "Death Lightning", SpellType.Incantation, SpellLocation.Base),
        new(6000, "Catch Flame", SpellType.Incantation, SpellLocation.Base),
        new(6001, "O- Flame!", SpellType.Incantation, SpellLocation.Base),
        new(6010, "Flame Sling", SpellType.Incantation, SpellLocation.Base),
        new(6020, "Flame- Fall Upon Them", SpellType.Incantation, SpellLocation.Base),
        new(6030, "Whirl- O Flame!", SpellType.Incantation, SpellLocation.Base),
        new(6040, "Flame- Cleanse Me", SpellType.Incantation, SpellLocation.Base),
        new(6050, "Flame- Grant Me Strength", SpellType.Incantation, SpellLocation.Base),
        new(6060, "Flame- Protect Me", SpellType.Incantation, SpellLocation.Base),
        new(6100, "Giantsflame Take Thee", SpellType.Incantation, SpellLocation.Base),
        new(6110, "Flame of the Fell God", SpellType.Incantation, SpellLocation.Base),
        new(6120, "Burn- O Flame!", SpellType.Incantation, SpellLocation.Base),
        new(6210, "Black Flame", SpellType.Incantation, SpellLocation.Base),
        new(6220, "Surge- O Flame!", SpellType.Incantation, SpellLocation.Base),
        new(6230, "Scouring Black Flame", SpellType.Incantation, SpellLocation.Base),
        new(6240, "Black Flame Ritual", SpellType.Incantation, SpellLocation.Base),
        new(6250, "Black Flame Blade", SpellType.Incantation, SpellLocation.Base),
        new(6260, "Black Flame's Protection", SpellType.Incantation, SpellLocation.Base),
        new(6270, "Noble Presence", SpellType.Incantation, SpellLocation.Base),
        new(6300, "Bloodflame Talons", SpellType.Incantation, SpellLocation.Base),
        new(6310, "Bloodboon", SpellType.Incantation, SpellLocation.Base),
        new(6320, "Bloodflame Blade", SpellType.Incantation, SpellLocation.Base),
        new(6330, "Barrier of Gold", SpellType.Incantation, SpellLocation.Base),
        new(6340, "Protection of the Erdtree", SpellType.Incantation, SpellLocation.Base),
        new(6400, "Rejection", SpellType.Incantation, SpellLocation.Base),
        new(6410, "Wrath of Gold", SpellType.Incantation, SpellLocation.Base),
        new(6420, "Urgent Heal", SpellType.Incantation, SpellLocation.Base),
        new(6421, "Heal", SpellType.Incantation, SpellLocation.Base),
        new(6422, "Great Heal", SpellType.Incantation, SpellLocation.Base),
        new(6423, "Lord's Heal", SpellType.Incantation, SpellLocation.Base),
        new(6424, "Erdtree Heal", SpellType.Incantation, SpellLocation.Base),
        new(6430, "Blessing's Boon", SpellType.Incantation, SpellLocation.Base),
        new(6431, "Blessing of the Erdtree", SpellType.Incantation, SpellLocation.Base),
        new(6440, "Cure Poison", SpellType.Incantation, SpellLocation.Base),
        new(6441, "Lord's Aid", SpellType.Incantation, SpellLocation.Base),
        new(6450, "Flame Fortification", SpellType.Incantation, SpellLocation.Base),
        new(6460, "Magic Fortification", SpellType.Incantation, SpellLocation.Base),
        new(6470, "Lightning Fortification", SpellType.Incantation, SpellLocation.Base),
        new(6480, "Divine Fortification", SpellType.Incantation, SpellLocation.Base),
        new(6490, "Lord's Divine Fortification", SpellType.Incantation, SpellLocation.Base),
        new(6510, "Assassin's Approach", SpellType.Incantation, SpellLocation.Base),
        new(6520, "Shadow Bait", SpellType.Incantation, SpellLocation.Base),
        new(6530, "Darkness", SpellType.Incantation, SpellLocation.Base),
        new(6600, "Golden Vow", SpellType.Incantation, SpellLocation.Base),
        new(6700, "Discus of Light", SpellType.Incantation, SpellLocation.Base),
        new(6701, "Triple Rings of Light", SpellType.Incantation, SpellLocation.Base),
        new(6710, "Radagon's Rings of Light", SpellType.Incantation, SpellLocation.Base),
        new(6720, "Elden Stars", SpellType.Incantation, SpellLocation.Base),
        new(6730, "Law of Regression", SpellType.Incantation, SpellLocation.Base),
        new(6740, "Immutable Shield", SpellType.Incantation, SpellLocation.Base),
        new(6750, "Litany of Proper Death", SpellType.Incantation, SpellLocation.Base),
        new(6760, "Law of Causality", SpellType.Incantation, SpellLocation.Base),
        new(6770, "Order's Blade", SpellType.Incantation, SpellLocation.Base),
        new(6780, "Order Healing", SpellType.Incantation, SpellLocation.Base),
        new(6800, "Bestial Sling", SpellType.Incantation, SpellLocation.Base),
        new(6810, "Stone of Gurranq", SpellType.Incantation, SpellLocation.Base),
        new(6820, "Beast Claw", SpellType.Incantation, SpellLocation.Base),
        new(6830, "Gurranq's Beast Claw", SpellType.Incantation, SpellLocation.Base),
        new(6840, "Bestial Vitality", SpellType.Incantation, SpellLocation.Base),
        new(6850, "Bestial Constitution", SpellType.Incantation, SpellLocation.Base),
        new(6900, "Lightning Spear", SpellType.Incantation, SpellLocation.Base),
        new(6910, "Ancient Dragons' Lightning Strike", SpellType.Incantation, SpellLocation.Base),
        new(6920, "Lightning Strike", SpellType.Incantation, SpellLocation.Base),
        new(6921, "Frozen Lightning Spear", SpellType.Incantation, SpellLocation.Base),
        new(6930, "Honed Bolt", SpellType.Incantation, SpellLocation.Base),
        new(6940, "Ancient Dragons' Lightning Spear", SpellType.Incantation, SpellLocation.Base),
        new(6941, "Fortissax's Lightning Spear", SpellType.Incantation, SpellLocation.Base),
        new(6950, "Lansseax's Glaive", SpellType.Incantation, SpellLocation.Base),
        new(6960, "Electrify Armament", SpellType.Incantation, SpellLocation.Base),
        new(6970, "Vyke's Dragonbolt", SpellType.Incantation, SpellLocation.Base),
        new(6971, "Dragonbolt Blessing", SpellType.Incantation, SpellLocation.Base),
        new(7200, "Pest Threads", SpellType.Incantation, SpellLocation.Base),
        new(7210, "Swarm of Flies", SpellType.Incantation, SpellLocation.Base),
        new(7220, "Poison Mist", SpellType.Incantation, SpellLocation.Base),
        new(7230, "Poison Armament", SpellType.Incantation, SpellLocation.Base),
        new(7240, "Scarlet Aeonia", SpellType.Incantation, SpellLocation.Base),
        new(7300, "Inescapable Frenzy", SpellType.Incantation, SpellLocation.Base),
        new(7310, "The Flame of Frenzy", SpellType.Incantation, SpellLocation.Base),
        new(7311, "Unendurable Frenzy", SpellType.Incantation, SpellLocation.Base),
        new(7320, "Frenzied Burst", SpellType.Incantation, SpellLocation.Base),
        new(7330, "Howl of Shabriri", SpellType.Incantation, SpellLocation.Base),
        new(7500, "Aspects of the Crucible: Tail", SpellType.Incantation, SpellLocation.Base),
        new(7510, "Aspects of the Crucible: Horns", SpellType.Incantation, SpellLocation.Base),
        new(7520, "Aspects of the Crucible: Breath", SpellType.Incantation, SpellLocation.Base),
        new(7530, "Black Blade", SpellType.Incantation, SpellLocation.Base),
        new(7900, "Fire's Deadly Sin", SpellType.Incantation, SpellLocation.Base),
        new(7903, "Golden Lightning Fortification", SpellType.Incantation, SpellLocation.Base),
        new(2006300, "Furious Blade of Ansbach", SpellType.Incantation, SpellLocation.Dlc),
        new(2006400, "Heal from Afar", SpellType.Incantation, SpellLocation.Dlc),
        new(2006650, "Aspects of the Crucible: Thorns", SpellType.Incantation, SpellLocation.Dlc),
        new(2006660, "Aspects of the Crucible: Bloom", SpellType.Incantation, SpellLocation.Dlc),
        new(2006670, "Minor Erdtree", SpellType.Incantation, SpellLocation.Dlc),
        new(2006680, "Land of Shadow", SpellType.Incantation, SpellLocation.Dlc),
        new(2006690, "Wrath from Afar", SpellType.Incantation, SpellLocation.Dlc),
        new(2006700, "Light of Miquella", SpellType.Incantation, SpellLocation.Dlc),
        new(2006710, "Multilayered Ring of Light", SpellType.Incantation, SpellLocation.Dlc),
        new(2006800, "Roar of Rugalea", SpellType.Incantation, SpellLocation.Dlc),
        new(2006900, "Knight's Lightning Spear", SpellType.Incantation, SpellLocation.Dlc),
        new(2006910, "Dragonbolt of Florissax", SpellType.Incantation, SpellLocation.Dlc),
        new(2006920, "Electrocharge", SpellType.Incantation, SpellLocation.Dlc),
        new(2007200, "Rotten Butterflies", SpellType.Incantation, SpellLocation.Dlc),
        new(2007210, "Pest-Thread Spears", SpellType.Incantation, SpellLocation.Dlc),
        new(2007300, "Midra's Flame of Frenzy", SpellType.Incantation, SpellLocation.Dlc),
        new(2007600, "Watchful Spirit", SpellType.Incantation, SpellLocation.Dlc),
        new(2007700, "Golden Arcs", SpellType.Incantation, SpellLocation.Dlc),
        new(2007710, "Giant Golden Arc", SpellType.Incantation, SpellLocation.Dlc),
        new(2007720, "Spira", SpellType.Incantation, SpellLocation.Dlc),
        new(2007730, "Divine Beast Tornado", SpellType.Incantation, SpellLocation.Dlc),
        new(2007740, "Divine Bird Feathers", SpellType.Incantation, SpellLocation.Dlc),
        new(2007800, "Fire Serpent", SpellType.Incantation, SpellLocation.Dlc),
        new(2007810, "Rain of Fire", SpellType.Incantation, SpellLocation.Dlc),
        new(2007820, "Messmer's Orb", SpellType.Incantation, SpellLocation.Dlc),
    };

    public static readonly SpellEntry[] DragonCommunionIncantations =
    {
        new(7000, "Dragonfire", SpellType.DragonCommunion, SpellLocation.Base),
        new(7001, "Agheel's Flame", SpellType.DragonCommunion, SpellLocation.Base),
        new(7010, "Magma Breath", SpellType.DragonCommunion, SpellLocation.Base),
        new(7011, "Theodorix's Magma", SpellType.DragonCommunion, SpellLocation.Base),
        new(7020, "Dragonice", SpellType.DragonCommunion, SpellLocation.Base),
        new(7021, "Borealis's Mist", SpellType.DragonCommunion, SpellLocation.Base),
        new(7030, "Rotten Breath", SpellType.DragonCommunion, SpellLocation.Base),
        new(7031, "Ekzykes's Decay", SpellType.DragonCommunion, SpellLocation.Base),
        new(7040, "Glintstone Breath", SpellType.DragonCommunion, SpellLocation.Base),
        new(7041, "Smarag's Glintstone Breath", SpellType.DragonCommunion, SpellLocation.Base),
        new(7050, "Placidusax's Ruin", SpellType.DragonCommunion, SpellLocation.Base),
        new(7060, "Dragonclaw", SpellType.DragonCommunion, SpellLocation.Base),
        new(7080, "Dragonmaw", SpellType.DragonCommunion, SpellLocation.Base),
        new(7090, "Greyoll's Roar", SpellType.DragonCommunion, SpellLocation.Base),
        new(2007000, "Bayle's Tyranny", SpellType.DragonCommunion, SpellLocation.Dlc),
        new(2007010, "Bayle's Flame Lightning", SpellType.DragonCommunion, SpellLocation.Dlc),
        new(2007020, "Ghostflame Breath", SpellType.DragonCommunion, SpellLocation.Dlc),
    };

    public static readonly SpellEntry[] AllSpells = Sorceries
        .Concat(Incantations)
        .Concat(DragonCommunionIncantations)
        .ToArray();

    // Remembrance spells: Enia-only (mirrors Athena's remembrances/*.csv)
    public static readonly SpellEntry[] RemembranceSorceries =
    {
        new(2004700, "Blades of Stone", SpellType.Sorcery, SpellLocation.Dlc),
        new(2004320, "Rellana's Twin Moons", SpellType.Sorcery, SpellLocation.Dlc),
        new(4360, "Rennala's Full Moon", SpellType.Sorcery, SpellLocation.Base),
        new(4830, "Rykard's Rancor", SpellType.Sorcery, SpellLocation.Base),
        new(2006200, "Vortex of Putrescence", SpellType.Sorcery, SpellLocation.Dlc),
    };

    public static readonly SpellEntry[] RemembranceIncantations =
    {
        new(7530, "Black Blade", SpellType.Incantation, SpellLocation.Base),
        new(6310, "Bloodboon", SpellType.Incantation, SpellLocation.Base),
        new(6120, "Burn- O Flame!", SpellType.Incantation, SpellLocation.Base),
        new(5040, "Death Lightning", SpellType.Incantation, SpellLocation.Base),
        new(6941, "Fortissax's Lightning Spear", SpellType.Incantation, SpellLocation.Base),
        new(2006680, "Land of Shadow", SpellType.Incantation, SpellLocation.Dlc),
        new(2006700, "Light of Miquella", SpellType.Incantation, SpellLocation.Dlc),
        new(2007820, "Messmer's Orb", SpellType.Incantation, SpellLocation.Dlc),
        new(2007300, "Midra's Flame of Frenzy", SpellType.Incantation, SpellLocation.Dlc),
        new(7050, "Placidusax's Ruin", SpellType.DragonCommunion, SpellLocation.Base),
        new(2007200, "Rotten Butterflies", SpellType.Incantation, SpellLocation.Dlc),
        new(7240, "Scarlet Aeonia", SpellType.Incantation, SpellLocation.Base),
    };

    public static readonly SpellEntry[] RemembranceSpells = RemembranceSorceries
        .Concat(RemembranceIncantations)
        .ToArray();

    public static readonly HashSet<int> RemembranceSpellIds = new(RemembranceSpells.Select(s => s.Id));

    // World spells: everything except remembrance (used for ItemLot map/enemy and normal shops)
    public static readonly SpellEntry[] WorldSpells = AllSpells
        .Where(s => !RemembranceSpellIds.Contains(s.Id))
        .ToArray();
}
